### ISSUE TITLE
Feedback for “Hive CLI (Command Line Interface)”

### ISSUE THREAD

**Issue by Wallman** [graphql-hive/platform#5615] opened 2024-09-20 06:57 UTC
Feedback on https://the-guild.dev/graphql/hive/docs/api-reference/cli

If `/usr/local/lib` does not exist (which it didn't for me or any of my colleagues) then `curl -sSL https://graphql-hive.com/install.sh | sh` fails silently.

We solved it with
```
cd /usr/local
sudo mkdir lib
```

but this should be improved.

**Comment by saihaj** [comment] 2024-10-03 20:59
what OS was this on?

**Comment by Wallman** [comment] 2024-10-04 07:00
> what OS was this on?

macOS Sonoma

**Comment by dotansimha** [comment] 2024-10-21 09:23
Duplicate of https://github.com/graphql-hive/platform/issues/3292

**Closed by dotansimha** 2024-10-21 09:23 UTC
Labels: bug
